### PR TITLE
feat: env expand contents

### LINKED ISSUE #719: Support env var expansion for `contents.src`
### Is your feature request related to a problem? Please describe.

I have a directory structure produced by Docker/BuildKit multi-platform build:
```
tmp/build/
├── linux_amd64
│   └── my-bin
└── linux_arm64
    └── my-bin
```

I want to be able to use the single `nfpm.yml` configuration file for both architectures. Unfortunately, it is not possible to use environment variable expansion in `contents.src`.

### Describe the solution you'd like

```yaml
arch: ${ARCH}
contents:
  - src: tmp/build/linux_${ARCH}/my-bin
    dst: /usr/bin/my-bin
```

### Describe alternatives you've considered

Using multiple `nfpm.yml` files. Using external templates. I would like to avoid both those alternatives.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I should be able to contribute that change if that's something you want to have.

### PR DESCRIPTION
**Pull request by caarlos0**
closes #719

### CODE REVIEW

**Comment by djgilcrease** [comment]
Careful with this as we have rejected this in the past because `$` is a valid path character. So we need tests for that and need to document that if a `$` is in the path it needs to be escaped.

**Review by AlekSi — APPROVED** [review]
:shipit:

**Comment by djgilcrease** [comment]
> Another option is to opt-in into expanding:
> 
I like this solution, that way it is explicit that the user knows it will expand env vars

**Comment by caarlos0** [comment]
pushed

**Review by djgilcrease — APPROVED** [review]
LGTM

**Pull request merged**
