### PR TITLE
feat: remove deprecated options

### PR DESCRIPTION
**Pull request by caarlos0**
regarding #255, removing the old options.

We will then version this as v2 (breaking change). Easier than keep a lot of things working.

Will still have to do the deprecation notice et all on goreleaser, but its on a single place then.

### CODE REVIEW

**Comment by caarlos0** [comment]
@djgilcrease I'm not sure why, but symlink tests on rpm and deb are failing 🤔 

I think it wasn't supposed to work before actually, since the actual file is never added to the package... does that makes sense?

**Comment by djgilcrease** [comment]
As part of this make sure you read https://blog.golang.org/v2-go-modules many people at my work have tried to bump to v2 but not read that and broken things in odd ways.

**Comment by caarlos0** [comment]
> As part of this make sure you read https://blog.golang.org/v2-go-modules many people at my work have tried to bump to v2 but not read that and broken things in odd ways.

yep, here's a picture of me reading it the last time I needed: 

image

😂

**Comment by caarlos0** [comment]
> As part of this make sure you read https://blog.golang.org/v2-go-modules many people at my work have tried to bump to v2 but not read that and broken things in odd ways.

In the past, I simply changed the module to `/v2` in `go.mod` (e.g. https://github.com/caarlos0/env), but yeah, they recommend a `v2` subfolder, which I absolutely hate and 0/10 will not do it. Just renaming works for go mod and non-go mod usage, but old versions won't work under go mods anymore (if I recall correctly).

Maybe just keep a v2 branch? Anyone with more experience with that?

**Comment by caarlos0** [comment]
> Other strategies may keep major versions on separate branches. However, if v2+ source code is on the repository's default branch (usually master), tools that are not version-aware — including the go command in GOPATH mode — may not distinguish between major versions.

IMHO ¯\_(ツ)_/¯ and we can just append `/v2` to the `go.mod` file... YOLO

**Comment by djgilcrease** [comment]
> > Other strategies may keep major versions on separate branches. However, if v2+ source code is on the repository's default branch (usually master), tools that are not version-aware — including the go command in GOPATH mode — may not distinguish between major versions.
> 
> IMHO ¯_(ツ)_/¯ and we can just append `/v2` to the `go.mod` file... YOLO

Ya that works, I don't really like the branch or sub folder method either, but it does make supporting older versions easier if we need to for some reason.

**Review by djgilcrease — APPROVED** [review]
LGTM

**Pull request merged**
