### PR TITLE
feat: create RPM without rpmbuild

### PR DESCRIPTION
**Pull request by djgilcrease**
Switch to using https://github.com/google/rpmpack (a pure go rpm builder) to build the RPM instead of rpmbuild.

Closes: #40

### CODE REVIEW

**Comment by caarlos0** [comment]
This is awesome, thanks!

Let's wait for that PR to be merged!

🙏

**Comment by caarlos0** [comment]
Thanks for the PR :D

**Comment by caarlos0** [comment]
seems like some tests are failing...

**Comment by caarlos0** [comment]
https://travis-ci.org/goreleaser/nfpm/builds/583296254

**Comment by rski** [comment]
to be honest, this change kinda scares me. From the rpmpack readme:
`May easily wreak havoc on rpm based systems. It is surprisingly easy to cause rpm to segfault on corrupt rpm files.`
D:

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
