### PR TITLE
fix: make epoch work again

### PR DESCRIPTION
**Pull request by marcsauter**
Epoch is already merged in google/rpmpack (https://github.com/google/rpmpack/commit/aa36bfddb3a0c725e19c73e75d76fea48882c399)

### CODE REVIEW

**Comment by marcsauter** [comment]
linter fails on things I didn't touch?

**Comment by caarlos0** [comment]
new linter version it seems, its broken on master too, I'll fix there...

meanwhile, can you add some tests?

thanks :)

**Comment by caarlos0** [comment]
fixed on master

**Comment by caarlos0** [comment]
thanks!

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
