### PR TITLE
feat: Support DEB Breaks field

### LINKED ISSUE #219: Suppport "Breaks" deb relationship
It would be great if nfpm supported the [`Breaks` relationship in debian packages](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-breaks)

### PR DESCRIPTION
**Pull request by erikgeiser**
This PR adds the `Break` field and an acceptance test. Closes #219.

### CODE REVIEW

**Comment by erikgeiser** [comment]
Oops, I accidentally auto-formatted the config in the docs. It looks nice through, so I think we should leave it like that.

**Comment by erikgeiser** [comment]
The tests are running out of time again, should I increase the limit to something like 15mins?

**Comment by caarlos0** [comment]
> The tests are running out of time again, should I increase the limit to something like 15mins?

sounds good

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
