### PR TITLE
WIP: feat(#42): Ability to have a changelog

### PR DESCRIPTION
**Pull request by djgilcrease**
**NOTE:** this will NOT create and maintain a changelog for you, you are expected to use https://github.com/goreleaser/chglog to generate and maintain the `changelog.yml` file, this will just read that file in and generate the correct changelog data for deb & rpm

dpkg does not provide any facility to read the changelog of a package. you should extract the package and read the changelog
`dpkg -X <package.deb> <folder>` then you can read the changelog using the dpkg-parsechangelog utility `dpkg-parsechangelog -l <folder>/usr/share/doc/<package>/changelog.Debian.gz`

rpm does provide a way to see the changelog `rpm -q --changelog path/to/pkg.rpm`

**TODO**
* [ ] get https://github.com/goreleaser/chglog to be building and releasing with goreleaser
* [ ] get feedback from @InTheCloudDan & @eugene-babichenko to ensure this meets their expectations

### CODE REVIEW

**Comment by caarlos0** [comment]
Overall, it looks good to me.

I only think that the NFPM API should only accept the changelog file and maintainer, and not try to guess anything. We could add those guesses to the cmd though.

I think that because once we integrate chlog with goreleaser, it will already have this info, so we may just pass it down to nfpm...

If running nfpm as a binary, adding this to the cmd should do the trick.

thoughts?

**Comment by djgilcrease** [comment]
Makes sense, will update this after Thanksgiving holiday

**Comment by erikgeiser** [comment]
Changelog support would be essential for me. Is this still in progress? If not, I could maybe look into it and try to fix the issues such that the pull request can be merged soon.

**Comment by erikgeiser** [comment]
I took a look at the pull request, implemented the requested changes, removed dependencies of specific commits of some packages and made it compatible with the master branch. Tomorrow I will take a look at some details such as tests. In a day or two I will submit a new pull request.

**Comment by caarlos0** [comment]
awesome, thanks @erikgeiser

**Comment by djgilcrease** [comment]
superseded by #158

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
