### PR TITLE
feat: add a keep_version flag

### PR DESCRIPTION
**Pull request by wellenvogel**
I'm using nfpm for some of my projects. As I already started other projects that also produce packages with a slightly different versioning schema (using other tools) I would like to have a chance to keep my version completely unchanged from the config to the created package.
To be fully compatible I introduced a flag to switch off the semver handling.

As I encountered problems when afterwards building a docker image I added a staticbuild task to the Makefile.

Working image at https://hub.docker.com/repository/docker/wellenvogel/nfpm: wellenvogel/nfpm:1.0

### CODE REVIEW

**Review by djgilcrease — CHANGES_REQUESTED** [review]
Looks good after a rebase

**Comment by caarlos0** [comment]
hey, thanks for the pr and sorry for the delay to review, lost it in the notifications I think...

---

I would say to do something more like:

```
version_schema: semver (default)|none
```

so its hopefully clearer.

wdyt?

---

also need to mention the new option in the docs...

**Comment by djgilcrease** [comment]
> ```
> version_schema: semver (default)|none
> ```

I like this, then I would change the check to a switch to make it easier to add additional version schema in the future.
```go
        switch info.VersionSchema {
            case "none":
                // No change to the version or prerelease info set in the YAML file
                break
            case "semver":
                fallthrough
            default:
                info.parseSemver()
        }
```

**Comment by caarlos0** [comment]
> I like this, then I would change the check to a switch to make it easier to add additional version schema in the future.

yep :)

**Comment by wellenvogel** [comment]
For me it also looks good.
Any solution that allows to set a plain version is completely ok.

**Review by djgilcrease — APPROVED** [review]

**Comment by djgilcrease** [comment]
Superceeded by #324

**Pull request closed without merging**
