### PR TITLE
feat: Allow for Arch to be specified via environment variable

### PR DESCRIPTION
**Pull request by nysan**
Signed-off-by: David Nyström <david.c.nystrom@gmail.com>

### CODE REVIEW

**Comment by erikgeiser** [comment]
Looks good to me

**Comment by caarlos0** [comment]
hey, thanks for the PR!

can you add a test for this? 

thanks! 🙏

**Comment by nysan** [comment]
There are more places where I need to do env variable subst(Versioned dependecies), and I'm leaning towards using "envsubst" from gettext-core instead of jumping through these hoops.
You can close this item from my perspective. Integrating this into nfpm is more of a convenience to avoid the package dependency.

**Comment by caarlos0** [comment]
Allright, thanks :)

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
