### PR TITLE
fix: relative paths to dirs

### LINKED ISSUE #575: Confusing behaviour with trailing `/` in destination
### What happened?

I have the following nfpm.yaml:

```yml
name: foo
version: 0.0.0
maintainer: asdf
arch: amd64
contents:
- dst: /usr/local/share/file/
  src: file.txt
```

Note the `/` at the end of the destination path. Because of that, I expect nfpm to install the file as `/usr/local/share/file/file.txt`. However, it installs the file as `/usr/local/share/file`. This is confusing because the trailing `/` indicates that the path is a directory, so the logical course of action would be to put the file into the directory.

### How can we reproduce this?

Copy the above nfpm.yaml, and create a file `file.txt`, and run `nfpm package -p deb`

### nfpm version

```bash
nfpm version nfpm version 2.22.0
commit: 5c3cc38943f1743bcaeb422c2dc65555fc9b12a1
built at: 2022-11-12T03:50:16Z
built by: goreleaser
module version: v2.22.0, checksum: h1:TC6tuxxFq0hL0WapI63+CkLMbcsYRbR7kAnLkRYAEbo=
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by caarlos0**
closes #575

### CODE REVIEW

**Review by djgilcrease — APPROVED** [review]
LGTM

**Comment by drakkan** [comment]
Hi,

this change broke my use case.

Please take a look [here](https://github.com/drakkan/sftpgo/blob/main/pkgs/build.sh#L77). 
I now have this error:

```
cannot add "/home/nicola/goprojects/sftpgo/templates/webclient/twofactor.html" because "/home/nicola/goprojects/sftpgo/templates/webadmin/twofactor.html" is already present at the same destination (/usr/share/sftpgo/templates/twofactor.html): content collision
```

I have some files with the same name in `templates/webclient` and `templates/webadmin`. Can I fix this by changing my glob syntax? (I've tried some alternate globs with no luck). Thanks

**Comment by caarlos0** [comment]
@drakkan yes, unfortunately this might be a breaking change for some... but I still think it was a bug before... I'll add a note about it in the readme though.

**Comment by caarlos0** [comment]
https://github.com/goreleaser/nfpm/releases/tag/v2.22.1

**Comment by drakkan** [comment]
> @drakkan yes, unfortunately this might be a breaking change for some... but I still think it was a bug before... I'll add a note about it in the release notes though.

no problem, thanks

**Pull request merged**
