### PR TITLE
feat: Add option for RPM compression type

### PR DESCRIPTION
**Pull request by AdrianWennberg**
Allows you to choose between gzip, xz, and lzma as the RPM compression type.

See #62

### CODE REVIEW

**Comment by AdrianWennberg** [comment]
Here's the documentation comment from `/usr/lib/rpm/macros` on my system for reference:
```
#       Compression type and level for source/binary package payloads.
#               "w9.gzdio"      gzip level 9 (default).
#               "w9.bzdio"      bzip2 level 9.
#               "w6.xzdio"      xz level 6, xz's default.
#               "w7T16.xzdio"   xz level 7 using 16 thread (xz only)
#               "w6.lzdio"      lzma-alone level 6, lzma's default
#
#%_source_payload       w9.gzdio
#%_binary_payload       w9.gzdio
```

**Comment by caarlos0** [comment]
can we default to one of them?

also would be nice to have tests covering this if you can :)

**Comment by AdrianWennberg** [comment]
It currently defaults to whatever your system defaults to, which I feel should be the default behavior, since most people are not going to want to override it. Also adding a default would change the behavior for people already using nfpm, unless they specify their own default.

I'll try to add some acceptance tests.

**Comment by caarlos0** [comment]
thanks for the contribution :D

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
