### PR TITLE
fix: Do not expand symlink on deb.

### PR DESCRIPTION
**Pull request by rsur**
See #183 

For deb only.

### CODE REVIEW

**Comment by erikgeiser** [comment]
I would also offer to create a pull request for `deb`/`rpm` symlinks based on my comments in #183, introducing a `symlinks:` config entry.

**Comment by erikgeiser** [comment]
I think this PR can be closed because #183 was fixed by #185.

**Comment by caarlos0** [comment]
Thanks everyone! 🚀

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
