### PR TITLE
docs: added docs website

### PR DESCRIPTION
**Pull request by caarlos0**
add website similar to the goreleaser one.

### CODE REVIEW

**Comment by nhooyr** [comment]
Why was `bindir` removed in this PR?

**Comment by caarlos0** [comment]
Because it was not used anymore, but I should have removed it in another pr...

**Comment by nhooyr** [comment]
> Because it was not used anymore, but I should have removed it in another pr...

All good, was just making sure it wasn't some mistake as we were using it and it was breaking our builds.

Would be good to document such breaking changes.

**Comment by caarlos0** [comment]
Good point, added to the release notes https://github.com/goreleaser/nfpm/releases/tag/v1.3.0

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
