### PR TITLE
fix: properly add the PostRemove script, not the PostInstall script

### PR DESCRIPTION
**Pull request by djgilcrease**

### CODE REVIEW

**Comment by caarlos0** [comment]
tests are failing, can you take a look @djgilcrease ?

I was too trigger-happy merging #67 and master is broken as well :/

**Comment by djgilcrease** [comment]
Will look. They all pass on my box locally :)

**Comment by djgilcrease** [comment]
So a few issues
1. Empty dirs were not being added
2. rpmpack does not support rpm config files which is what creates the .rpmsave file so I commented out all `RUN test -f /etc/foo/whatever.conf.rpmsave` in the docker files
   * https://github.com/google/rpmpack/pull/16 will fix this
3. rpmpack does not support anything but gzip, so I commented out the `TestRPMCompression`
   * https://github.com/google/rpmpack/pull/16 will fix this

I will create a followup MR that will fix the two issues where I had to comment out tests

**Comment by caarlos0** [comment]
awesome, lets wait for that PR :D 

Thanks @djgilcrease 🙏

**Comment by djgilcrease** [comment]
Opened a WIP PR that includes all the other enhancements and fixes the PR to `rpmpack` enables

**Comment by djgilcrease** [comment]
Closing this in favor of a more complete fix coming when my final changes get merged to `rpmpack`

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
