### PR TITLE
refactor: internal/files

### PR DESCRIPTION
**Pull request by caarlos0**
refs https://github.com/goreleaser/nfpm/pull/186/files#r464765660

In theory, no one was supposed to be using that public method. Will not bump major because of that, its a risk I'm willing to take.

### CODE REVIEW

**Comment by erikgeiser** [comment]
I see you moved the "old" `FilesToCopy` function to `ToCopy` in the `internal` package. We could either include the changes made in #186 to this function (and the `FileToCopy` struct) already in this PR or I rebase #186 as soon as this PR gets merged.

**Comment by caarlos0** [comment]
yes, can you rebase? if not I can do it... but should be fine :) 

thanks

**Comment by erikgeiser** [comment]
already done

**Comment by caarlos0** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
