### PR TITLE
fix(archlinux): .MTREE should have parent dirs as well

### PR DESCRIPTION
**Pull request by caarlos0**
this walks up the destination and creates the `.MTREE` entries for the parents too, otherwise packages are not installable by `pacman`.

if anyone knows a better way to do this, I'm all ears... 

closes https://github.com/goreleaser/nfpm/issues/638

### CODE REVIEW

**Comment by erikgeiser** [comment]
I can’t really review this PR right now but from a first glance I think this should be fixed in our files library. There we create implicit directories (a dedicated content type) that we add for debs but not for rpms. So arch packages should work like debs in this regard.

**Comment by erikgeiser** [comment]
We probably just need to add implicit dirs in the content type switch in WriteTo.

**Comment by erikgeiser** [comment]
This should do the trick:
```go
 func (me *MtreeEntry) WriteTo(w io.Writer) (int64, error) {
        switch me.Type {
-   case files.TypeDir:
+ case files.TypeDir, files.TypeImplicitDir:
                n, err := fmt.Fprintf(
                        w,
                        "./%s time=%d.0 mode=%o type=dir\n",
```

However, the test does take the `info.Contents` into account. In my opinion, the `TestArchMtree` test should not check for implicit directories. We should add another test, that builds the entire package and then checks if the mtree contains implicit directories.

I'm sorry, but I don't have the time to rewrite the test, otherwise I would have already pushed the diff above.

**Comment by caarlos0** [comment]
> This should do the trick:
> 
> ```go
>  func (me *MtreeEntry) WriteTo(w io.Writer) (int64, error) {
>         switch me.Type {
> -   case files.TypeDir:
> + case files.TypeDir, files.TypeImplicitDir:
>                 n, err := fmt.Fprintf(
>                         w,
>                         "./%s time=%d.0 mode=%o type=dir\n",
> ```
> 
> However, the test does take the `info.Contents` into account. In my opinion, the `TestArchMtree` test should not check for implicit directories. We should add another test, that builds the entire package and then checks if the mtree contains implicit directories.
> 
> I'm sorry, but I don't have the time to rewrite the test, otherwise I would have already pushed the diff above.

ah way better indeed, will work on it, thanks!

**Comment by caarlos0** [comment]
@erikgeiser fwiw that doesn't work, will look into why later... but the root folders are still missing there...

**Comment by erikgeiser** [comment]
Yeah I missed this one:
https://github.com/goreleaser/nfpm/blob/571a32b031d06d03fb7cbfab007f2506576c3f08/arch/arch.go#L177
The mtree entry should always be added.

**Comment by caarlos0** [comment]
Ah right, I'm 100% blind 😂

**Comment by caarlos0** [comment]
ight, all fixed, thanks for the help @erikgeiser

**Pull request merged**
